Making liquibase change to take care of null value in global propert… (#66)
* Making liquibase change to take care of null value in global property and added trigger

* Updating liquibase to insert ABHA and ABHA address

diff --git a/.github/workflows/build_and_upload.yml b/.github/workflows/build_and_upload.yml
--- a/.github/workflows/build_and_upload.yml
+++ b/.github/workflows/build_and_upload.yml
@@ -35,3 +35,24 @@ jobs:
       with:
         name: Package
         path: staging
+
+  trigger-dependent-repos:
+    name: Trigger Workflows
+    needs: build
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        dependent-repos: [ 'bahmni-india-package' ]
+    steps:
+      - name: Create repository_dispatch
+        env:
+          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
